### ISSUE TITLE
java.io.IOException: Failed on local exception: com.google.protobuf.InvalidProtocolBufferException: Protocol message contained an invalid tag (zero)

### ISSUE THREAD

**Issue by xelllee** [ptgoetz/storm-hdfs#1]
2014-02-04 11:28:27 b.s.util [ERROR] Async loop died!
java.lang.RuntimeException: Error preparing HdfsBolt: Failed on local exception: com.google.protobuf.InvalidProtocolBufferException: Protocol message contained an invalid tag (zero).; Host Details : loc
al host is: "xxxx"; destination host is: "xxxx":8020; 
    at org.apache.storm.hdfs.trident.HdfsState.prepare(HdfsState.java:92) ~[stormjar.jar:na]
    at org.apache.storm.hdfs.trident.HdfsStateFactory.makeState(HdfsStateFactory.java:27) ~[stormjar.jar:na]
    at storm.trident.planner.SubtopologyBolt.prepare(SubtopologyBolt.java:52) ~[storm-core-0.9.0.1.jar:na]
    at storm.trident.topology.TridentBoltExecutor.prepare(TridentBoltExecutor.java:214) ~[storm-core-0.9.0.1.jar:na]
    at backtype.storm.daemon.executor$fn__3498$fn__3510.invoke(executor.clj:674) ~[storm-core-0.9.0.1.jar:na]
    at backtype.storm.util$async_loop$fn__444.invoke(util.clj:401) ~[storm-core-0.9.0.1.jar:na]
    at clojure.lang.AFn.run(AFn.java:24) [clojure-1.4.0.jar:na]
    at java.lang.Thread.run(Thread.java:662) [na:1.6.0_37]
###### 
###### 

try{
            Configuration hdfsConfig = new Configuration();
            this.fs = FileSystem.get(URI.create(this.options.fsUrl), hdfsConfig);
            out = this.fs.create(new Path(this.options.path, this.options.fileNameFormat.getName(this.rotation, System.currentTimeMillis())));
        } catch (Exception e){
            throw new RuntimeException("Error preparing HdfsBolt: " + e.getMessage(), e);
        }

**Comment by ptgoetz** [comment]
What version of hadoop are you running against?

**Comment by xelllee** [comment]
test on the trident sample code
########

```
   TransactionalTridentKafkaSpout kafkaSpout = new TransactionalTridentKafkaSpout(kafkaConfig);
    TridentTopology topology = new TridentTopology();


    Fields hdfsFields = new Fields("str");
    FileNameFormat fileNameFormat = new DefaultFileNameFormat().withPrefix("trident").withExtension(".txt");

    RecordFormat recordFormat = new DelimitedRecordFormat().withFields(hdfsFields);


    FileRotationPolicy rotationPolicy = new FileSizeRotationPolicy(5.0f, FileSizeRotationPolicy.Units.MB);

    HdfsState.Options options = new HdfsState.Options()
            .withFileNameFormat(fileNameFormat)
            .withRecordFormat(recordFormat)
            .withRotationPolicy(rotationPolicy)
            .withFsUrl("hdfs://xxxx:8020")
            .withPath("/trident");


    StateFactory factory = new HdfsStateFactory().withOptions(options);


    TridentState wordCoutns =
            topology.newStream("kafka", kafkaSpout).partitionPersist(factory, hdfsFields, new HdfsUpdater(), new Fields());
```

##################
2014-02-04 13:29:06 b.s.d.executor [ERROR] 
java.lang.RuntimeException: Error preparing HdfsBolt: No FileSystem for scheme: hdfs
    at org.apache.storm.hdfs.trident.HdfsState.prepare(HdfsState.java:92) ~[stormjar.jar:na]
    at org.apache.storm.hdfs.trident.HdfsStateFactory.makeState(HdfsStateFactory.java:27) ~[stormjar.jar:na]
    at storm.trident.planner.SubtopologyBolt.prepare(SubtopologyBolt.java:52) ~[storm-core-0.9.0.1.jar:na]
    at storm.trident.topology.TridentBoltExecutor.prepare(TridentBoltExecutor.java:214) ~[storm-core-0.9.0.1.jar:na]
    at backtype.storm.daemon.executor$fn__3498$fn__3510.invoke(executor.clj:674) ~[storm-core-0.9.0.1.jar:na]
    at backtype.storm.util$async_loop$fn__444.invoke(util.clj:401) ~[storm-core-0.9.0.1.jar:na]
    at clojure.lang.AFn.run(AFn.java:24) [clojure-1.4.0.jar:na]
    at java.lang.Thread.run(Thread.java:662) [na:1.6.0_37]
Caused by: java.io.IOException: No FileSystem for scheme: hdfs
    at org.apache.hadoop.fs.FileSystem.getFileSystemClass(FileSystem.java:2296) ~[stormjar.jar:na]
    at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:2303) ~[stormjar.jar:na]
    at org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:87) ~[stormjar.jar:na]
    at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:2342) ~[stormjar.jar:na]
    at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:2324) ~[stormjar.jar:na]
    at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:351) ~[stormjar.jar:na]
    at org.apache.storm.hdfs.trident.HdfsState.prepare(HdfsState.java:89) ~[stormjar.jar:na]
    ... 7 common frames omitted

**Comment by ptgoetz** [comment]
For the first issue, in your pom try excluding the hadoop dependencies from storm-hdfs, then add the CDH dependencies in your pom.

For the second issue, it looks like you're using the maven assembly plugin to create your topology jar. The assembly plugin will mess up the metadata that the hadoop client uses for scheme resolution, so you should use the maven shade plugin like so:

``` xml
<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-shade-plugin</artifactId>
    <version>1.4</version>
    <configuration>
        <createDependencyReducedPom>true</createDependencyReducedPom>
    </configuration>
    <executions>
        <execution>
            <phase>package</phase>
            <goals>
                <goal>shade</goal>
            </goals>
            <configuration>
                <transformers>
                    <transformer
                            implementation="org.apache.maven.plugins.shade.resource.ServicesResourceTransformer"/>
                    <transformer
                            implementation="org.apache.maven.plugins.shade.resource.ManifestResourceTransformer">
                        <mainClass></mainClass>
                    </transformer>
                </transformers>
            </configuration>
        </execution>
    </executions>
</plugin>

```

**Comment by xelllee** [comment]
Thanks for your quick response and nice work, it works as expected. : )

**Comment by ptgoetz** [comment]
README updated to reflect this issue/solution.

**Comment by surya-github** [comment]
I tried to compile using CDH Libraries but i got the following error

[ERROR] storm-hdfs/src/main/java/org/apache/storm/hdfs/bolt/HdfsBolt.java:[27,57] cannot find symbol
symbol  : class SyncFlag
[ERROR] storm-hdfs/src/main/java/org/apache/storm/hdfs/trident/HdfsState.java:[156,90] cannot find symbol
[ERROR] symbol  : variable SyncFlag

which is missing in the CDH hadoop-client.jar implementation of following class
org.apache.hadoop.hdfs.client.HdfsDataOutputStream.SyncFlag
is there any workaround solution for this?
